### ISSUE TITLE
BETA/GOLD TODO (code)

### ISSUE THREAD

**Issue by trxe** [CS3247-Game-Development-Team-6/Doodles#235]
- [ ] Level progress save and continue (via PlayerPrefs)
- [x] #254
- [x] Improve Map Chunk start point algorithm
- [x] Active effects
- [x] Towers
  - [x] Mortar
  - [x] Landmine
  - [x] Laser
- [x] UI revamp
  - [x] Better HUD for strategy
  - [x] Loadout
