### ISSUE TITLE
Assets todo

### ISSUE THREAD

**Issue by trxe** [CS3247-Game-Development-Team-6/Doodles#31]
- [x] Implement outline shader
- [ ] Create 3D assets
  - [ ] ~~Enemy x 3 (min 1)~~ [POSTPONED]
  - [ ] ~~Tower x 3 x 2 (upgrade)~~ [POSTPONED]
  - [x] Fog
  - [x] Plane (base texture paper)
  - [x] “Hand drawn” squares for grid
  - [x] Home base x 3 (1x1 tile)
  - [x] Water Fire Ice Electric effects (Elements)
- [x] Create player sprite
